"""Module for holding global constant values"""

################################
# Constants for ADS WECC mapping 
################################

# maps ADS tech name to PyPSA name 
ADS_TECH_MAPPER= {
    'Solar_Tracking':'solar-utility',
    'NG_Industrial':'OCGT', 
    'NG_Areo':'OCGT',
    'Wind_Onshore':'onwind',
    'Geo_Binary':'geothermal', 
    'Solar_CSP6':'central solar thermal', 
    'NG_Single shaft':'OCGT', 
    'Solar_CSP0':'central solar thermal',
    'Geo_Double flash':'geothermal',
    'Solar_Photovoltaic':'solar-utility',
    'Natural Gas_Steam Turbine':'CCGT',
    'Subbituminous Coal_Steam Turbine':'coal',
    'Water_Hydraulic Turbine':'hydro', 
    'Natural Gas_Gas Turbine':'OCGT',
    'Wind_Wind Turbine':'onwind', 
    'MWH_Battery Storage':'battery storage', 
    'Nuclear_Nuclear':'nuclear',
    'Solar_NonTracking':'solar-utility', 
    'Landfill Gas_Internal Combustion':'other',
    'Electricity_Battery Storage':'battery storage', 
    'Solar_Non-Tracking':'solar-utility', 
    'DFO_ICE':'oil',
    'OBG_GT-NG':'other', 
    'DFO_ST':'oil', 
    'WDS_ST':'biomass',
    'Solar_Fixed':'solar-utility',
    'NG_Aero':'OCGT',
    'Biomass Waste_Internal Combustion':'biomass', 
    'OBG_ICE':'other',
    'LFG_ICE':'waste',
    'NG_GT-NG':'OCGT',
    'Wind_WT':'onwind',
    'Natural Gas_Combined Cycle':'CCGT',
    'Uranium_Nuclear':'nuclear',
    'Electricity_Non-Tracking':'battery storage',
}

# maps ADS sub-type tech name to PyPSA name 
ADS_SUB_TYPE_TECH_MAPPER = {
    'SolarPV-Tracking':'solar-utility',
    'CT-NatGas-Industrial':'OCGT',
    'CT-NatGas-Aero':'OCGT',
    'Hydro':'hydro',
    'Bio-ICE':'biomass',
    'PS-Hydro':'hydro',
    'SolarPV-NonTracking':'solar-utility',
    'WT-Onshore':'onwind',
    'Bio-ST':'CCGT',
    'ST-WasteHeat':'CCGT',
    'Geo-BinaryCycle':'geothermal',
    'ST-NatGas':'CCGT',
    'SolarThermal-CSP6':'central solar thermal',
    'CCWhole-NatGas-SingleShaft':'CCGT',
    'ICE-NatGas':'OCGT',
    'HydroRPS':'hydro',
    'ST-Nuclear':'nuclear',
    'Bio-CT':'biomass',
    'ST-Other':'CCGT',
    'CT-OilDistillate':'oil',
    'ST-Coal':'coal',
    'CCWhole-NatGas-Aero':'CCGT',
    'Bio-CC':'biomass',
    'CCWhole-NatGas-Industrial':'CCGT',
    'SolarThermal-CSP0':'central solar thermal',
    'PS-HydroRPS':'hydro',
    'Battery Storage':'battery storage',
    'Geo-DoubleFlash':'geothermal',
    'ICE-OilDistillate':'oil',
    'HYDRO':'hydro',
    'CT-Aero':'OCGT',
    'DR':'demand response',
    'MotorLoad':'other',
    'DG-BTM':'solar-rooftop',
    'CT-AB-Cogen':'OCGT',
    'CCPart-Steam':'CCGT',
    'CC-AB-Cogen':'CCGT',
    'UnknownPwrFloMdl':'other',
    'hydro':'hydro',
    'DC-Intertie':'other',
    'VAR-Device':'other'
}

# maps ADS carrier names to PyPSA name 
ADS_CARRIER_NAME = {
    'Solar':'solar',
    'NG':'gas', 
    'Water':'hydro', 
    'Bio':'biomass', 
    'Wind':'wind', 
    'WH':'waste',
    'Geo':'geothermal',
    'Uranium':'nuclear',
    'Petroleum Coke':'oil',
    'Coal':'coal',
    'NatGas':'gas',
    'Oil':'oil',
    'Electricity':'battery',
    'Natural Gas':'gas',
    'Subbituminous Coal':'coal',
    'Combined Cycle':'gas',
    'MWH':'battery',
    'Nuclear':'nuclear',
    'Landfill Gas':'waste',
    'DFO':'oil',
    'OBG':'other',
    'WDS':'biomass',
    'Biomass Waste':'waste',
    'LFG':'waste'
}

# maps ADS fuel name to PyPSA name 
ADS_FUEL_MAPPER = {
    'Solar':'Solar',
    'NG':'Gas',
    'Water':'Hydro',
    'Bio':'Biomass',
    'Wind':'Wind',
    'WH':'Waste', ##TODO: #33 add waste into cost data
    'Geo': 'Geothermal',
    'Uranium':'Nuclear',
    'Petroleum Coke':'Oil',
    'Coal':'Coal',
    'NatGas':'Gas',
    'Oil':'Oil',
    'Electricity':'Battery',
    'Natural Gas':'Gas',
    'Subbituminous Coal':'Coal',
    'Combined Cycle':'Gas_CC',
    'MWH':'Battery',
    'Nuclear':'Nuclear',
    'Landfill Gas':'Waste',
    'DFO':'Oil',
    'OBG':'Other',
    'WDS':'Biomass',
    'Biomass Waste':'Biomass',
    'LFG':'Waste',
}