name: Bug Report
description: Create a report if something doesn't work quite right.
# title: ""
labels: ["bug"]
# assignees:
#   -
body:

- type: checkboxes
  attributes:
    label: Checklist
    description: Code and environment checks
    options:
    - label: I am using the current [`master`](https://github.com/PyPSA/pypsa-usa/tree/master) branch
      required: true
    - label: I am running on an up-to-date [`pypsa-usa` environment](https://github.com/PyPSA/pypsa-usa/blob/master/workflow/envs/environment.yaml). Update via `conda env update -f envs/environment.yaml`
      required: true

- type: textarea
  attributes:
    label: The Issue
    description: Provide a concise description of what the bug is
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Add a minimal example/command for reproducing the bug
    placeholder: |
      1. Running this command...
      2. With this config.yaml file data...
      3. I get an error in this rule...
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false

- type: textarea
  id: error
  attributes:
    label: Error Message
    description: |
      If applicable, paste any terminal output to help illustrating your problem.
      In some cases it may also be useful to share your list of installed packages: `conda list`
      This will be automatically formatted into code, so no need for backticks.
    render: shell
  validations:
    required: false

  # - type: dropdown
  #   id: os
  #   attributes:
  #     label: Operating System
  #     description: What operating system are you running?
  #     options:
  #       - Linux
  #       - MacOS
  #       - Windows
  #   validations:
  #     required: true

  # - type: input
  #   id: version
  #   attributes:
  #     label: What version of PyPSA-USA are you running?
  #   validations:
  #     required: true

  # - type: textarea
  #   id: solution
  #   attributes:
  #     label: Possible Solution
  #     description: Do you have an idea on how to fix the issue?
  #   validations:
  #     required: false

- type: textarea
  id: other
  attributes:
    label: Anything else?
    description: |
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
