"""Same-branch A/B harness for ``electricity.demand.bus_allocation``.

Builds the candidate pipeline twice from configs derived off
``config.equivalence.yaml`` — run ``ab_pd`` pins the legacy Breakthrough
``Pd`` weight, run ``ab_pop`` the 2020-census population weight — then
compares artifacts at the same relative paths under the two run prefixes.

Unlike the candidate-vs-anchor equivalence run, differences here are the
*product*: the report characterizes how demand allocation shifts (per state /
county / bus) and what that does to clustering and the solve. Only two things
are hard invariants and gate the exit code:

- substation-level topology is identical (weights cannot move buses/lines);
- per-state demand totals scale exactly with the state's in-network LAF share
  (bus demand = state profile x LAF_state, so total_pop/total_pd must equal
  sum(LAF)_pop/sum(LAF)_pd to float precision — the allocation plumbing
  conserves demand; only the weight source moves it).

Usage::

    uv run python -m tests.equivalence.ab [--skip-solve] [--skip-build] [--jobs N]
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import shutil
import sys
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO))

from tests.equivalence.build import log, run, snakemake_cmd  # noqa: E402
from tests.equivalence.compare import _rel_pct, load_network  # noqa: E402
from tests.equivalence.paths import (  # noqa: E402
    CLUSTERS,
    INTERCONNECT,
    LL,
    OPTS,
    SECTOR,
)

WF = REPO / "workflow"
OUT_DIR = WF / "results" / "ab"

# scope: 'ca' = the equivalence config as-is (CA-only, 4 zones);
# 'western' = drop the CA topology filter, clusters = the 33 western
# ReEDS zones (transmission_network=reeds needs clusters == zone count)
SCOPES = {
    "ca": {"suffix": "", "clusters": CLUSTERS, "drop_topology_filter": False},
    "western": {"suffix": "_west", "clusters": "33", "drop_topology_filter": True},
}
SCOPE = "ca"
AB_CLUSTERS = CLUSTERS
BASELINE, VARIANT, REPLICA = "ab_pd", "ab_pop", "ab_pop2"
PREPARED = f"elec_s_c{AB_CLUSTERS}_ec_l{LL}_{OPTS}_{SECTOR}"
REPORT_STEM = "ab_report"


def set_scope(scope: str) -> None:
    global SCOPE, AB_CLUSTERS, BASELINE, VARIANT, REPLICA, PREPARED, REPORT_STEM
    SCOPE = scope
    cfg = SCOPES[scope]
    AB_CLUSTERS = cfg["clusters"]
    sfx = cfg["suffix"]
    BASELINE, VARIANT, REPLICA = f"ab_pd{sfx}", f"ab_pop{sfx}", f"ab_pop2{sfx}"
    PREPARED = f"elec_s_c{AB_CLUSTERS}_ec_l{LL}_{OPTS}_{SECTOR}"
    REPORT_STEM = "ab_report" if scope == "ca" else f"ab_report_{scope}"


def sides() -> dict:
    return {BASELINE: "breakthrough", VARIANT: "population"}


# conservation tolerance for "identical" demand totals (float roundtrip noise)
CONSERVED_RTOL = 1e-9


# ---------------------------------------------------------------- build side
def seed_workflow_configs() -> None:
    """Seed gitignored layered configs from repo_data (fresh worktrees)."""
    src_root = WF / "repo_data" / "config"
    dst_root = WF / "config"
    for entry in src_root.iterdir():
        dst = dst_root / entry.name
        if dst.exists():
            continue
        if entry.is_dir():
            shutil.copytree(entry, dst)
        else:
            shutil.copy2(entry, dst)


def derive_config(run_name: str, method: str) -> str:
    """Write config.{run_name}.yaml derived from config.equivalence.yaml."""
    base = WF / "repo_data" / "config" / "config.equivalence.yaml"
    cfg = yaml.safe_load(base.read_text())
    cfg["run"]["name"] = run_name
    cfg.setdefault("electricity", {}).setdefault("demand", {})["bus_allocation"] = method
    if SCOPES[SCOPE]["drop_topology_filter"]:
        cfg.get("model_topology", {}).pop("include", None)
    cfg["scenario"]["clusters"] = [int(AB_CLUSTERS)]
    out = WF / "config" / f"config.{run_name}.yaml"
    out.write_text(
        f"# GENERATED by tests/equivalence/ab.py — do not edit; derived from\n"
        f"# repo_data/config/config.equivalence.yaml with run.name={run_name}, "
        f"bus_allocation={method}\n" + yaml.safe_dump(cfg, sort_keys=False),
    )
    return f"config/config.{run_name}.yaml"


def target(run_name: str, solve: bool) -> str:
    if solve:
        return f"results/{run_name}/{INTERCONNECT}/networks/{PREPARED}.nc"
    return f"resources/{run_name}/networks/{INTERCONNECT}/{PREPARED}.nc"


def build(run_name: str, method: str, solve: bool, jobs: int) -> None:
    configfile = derive_config(run_name, method)
    tgt = target(run_name, solve)
    t0 = time.time()
    cp = run(snakemake_cmd(tgt, jobs, configfile), cwd=WF, timeout=14400)
    if cp.returncode != 0:
        tail = "\n".join((cp.stderr or cp.stdout).splitlines()[-120:])
        raise RuntimeError(f"{run_name} snakemake failed (exit {cp.returncode}):\n{tail}")
    log(f"{run_name} ({method}) build OK in {time.time() - t0:.0f}s")


# ------------------------------------------------------------- analysis side
def sub_network(run_name: str):
    return load_network(WF / f"resources/{run_name}/networks/{INTERCONNECT}/elec_s_l_pp.pkl")


def mean_load_by_bus(n) -> pd.DataFrame:
    """Mean MW per load bus with bus metadata (state, reeds_zone)."""
    mw = n.loads_t.p_set.mean()
    mw.index = mw.index.map(lambda name: str(n.loads.at[name, "bus"]))
    mw = mw.groupby(level=0).sum()
    meta = n.buses[["reeds_state", "reeds_zone"]].copy()
    meta.index = meta.index.map(str)
    return meta.join(mw.rename("mw"), how="left").fillna({"mw": 0.0})


def analyze(solve: bool) -> dict:
    npd, npop = sub_network(BASELINE), sub_network(VARIANT)
    res: dict = {"invariants": [], "tables": {}, "stats": {}}

    # -- invariant: identical substation topology
    same_buses = set(map(str, npd.buses.index)) == set(map(str, npop.buses.index))
    same_lines = set(map(str, npd.lines.index)) == set(map(str, npop.lines.index))
    res["invariants"].append(
        {
            "name": "substation topology identical (buses & lines)",
            "ok": bool(same_buses and same_lines),
            "detail": f"buses match: {same_buses}, lines match: {same_lines}",
        },
    )

    dpd, dpop = mean_load_by_bus(npd), mean_load_by_bus(npop)
    df = dpd.rename(columns={"mw": "mw_pd"}).join(dpop[["mw"]].rename(columns={"mw": "mw_pop"}))
    df["delta_mw"] = df.mw_pop - df.mw_pd
    with np.errstate(divide="ignore", invalid="ignore"):
        df["delta_pct"] = np.where(df.mw_pd > 0, 100 * df.delta_mw / df.mw_pd, np.nan)

    # -- invariant: per-state demand totals scale exactly with the state's
    # in-network LAF share (bus demand = state profile x LAF_state; LAF_state
    # is dropped downstream of add_demand, so read it from the base network).
    def laf_sum(run_name):
        import pypsa

        nb = pypsa.Network(
            str(WF / f"resources/{run_name}/networks/{INTERCONNECT}/elec_base_network.nc"),
        )
        return nb.buses.LAF_state.fillna(0).groupby(nb.buses.reeds_state).sum()

    lpd, lpop = laf_sum(BASELINE), laf_sum(VARIANT)
    by_state = df.groupby("reeds_state")[["mw_pd", "mw_pop"]].sum()
    by_state["laf_sum_pd"] = lpd.reindex(by_state.index)
    by_state["laf_sum_pop"] = lpop.reindex(by_state.index)
    by_state["delta_pct"] = 100 * (by_state.mw_pop - by_state.mw_pd) / by_state.mw_pd
    mw_ratio = by_state.mw_pop / by_state.mw_pd
    laf_ratio = by_state.laf_sum_pop / by_state.laf_sum_pd
    bad = by_state[~np.isclose(mw_ratio, laf_ratio, rtol=1e-6)]
    res["invariants"].append(
        {
            "name": "state demand scales exactly with LAF share (allocation conserved)",
            "ok": bad.empty,
            "detail": (
                "all states consistent"
                if bad.empty
                else f"violated for {list(bad.index)}: mw ratio vs LAF ratio diverge"
            ),
        },
    )
    res["tables"]["by_state"] = by_state.round(4)

    # -- characterization: reallocation by zone / county / bus. Peaks matter
    # because extendable peaker capacity (e.g. OCGT) tracks the zone peak.
    def zone_peak(n):
        p = n.loads_t.p_set.T.groupby(n.loads.bus.astype(str)).sum().T
        zones = n.buses.reeds_zone.astype(str)
        return p.T.groupby(zones.reindex(p.columns)).sum().T.max()

    by_zone = df.groupby("reeds_zone")[["mw_pd", "mw_pop"]].sum()
    by_zone["delta_pct"] = 100 * (by_zone.mw_pop - by_zone.mw_pd) / by_zone.mw_pd
    by_zone["peak_pd"] = zone_peak(npd).reindex(by_zone.index)
    by_zone["peak_pop"] = zone_peak(npop).reindex(by_zone.index)
    by_zone["peak_delta_mw"] = by_zone.peak_pop - by_zone.peak_pd
    res["tables"]["by_zone"] = by_zone.round(4)

    movers = df.reindex(df.delta_mw.abs().sort_values(ascending=False).index)
    res["tables"]["top_bus_movers"] = movers.head(20).round(3)

    load_buses_pd = int((df.mw_pd > 0).sum())
    load_buses_pop = int((df.mw_pop > 0).sum())
    res["stats"].update(
        {
            "n_buses": len(df),
            "load_buses_pd": load_buses_pd,
            "load_buses_pop": load_buses_pop,
            "total_mw_pd": float(df.mw_pd.sum()),
            "total_mw_pop": float(df.mw_pop.sum()),
            "total_delta_pct": _rel_pct(df.mw_pop.sum(), df.mw_pd.sum()),
            "mean_abs_bus_shift_mw": float(df.delta_mw.abs().mean()),
        },
    )
    res["bus_frame"] = df
    res["weight_share"] = pd.DataFrame(
        {
            "pd": 100 * npd.buses.load_weight.fillna(0) / npd.buses.load_weight.fillna(0).sum(),
            "pop": 100 * npop.buses.load_weight.fillna(0) / npop.buses.load_weight.fillna(0).sum(),
        },
    ).set_axis(npd.buses.index.map(str))

    # -- characterization: clustered + solved stages
    for stage, rel in (
        ("clustered", f"resources/{{run}}/networks/{INTERCONNECT}/elec_s_c{AB_CLUSTERS}.nc"),
        ("solved", f"results/{{run}}/{INTERCONNECT}/networks/{PREPARED}.nc"),
    ):
        if stage == "solved" and not solve:
            continue
        ppd, ppop = (WF / rel.format(run=r) for r in (BASELINE, VARIANT))
        if not (ppd.exists() and ppop.exists()):
            log(f"skipping {stage} comparison (artifact missing)")
            continue
        ncd, ncp = load_network(ppd), load_network(ppop)
        if stage == "clustered":
            cl = pd.DataFrame(
                {
                    "load_mw_pd": ncd.loads_t.p_set.mean().groupby(ncd.loads.bus.astype(str)).sum(),
                    "load_mw_pop": ncp.loads_t.p_set.mean().groupby(ncp.loads.bus.astype(str)).sum(),
                },
            )
            cl["delta_pct"] = 100 * (cl.load_mw_pop - cl.load_mw_pd) / cl.load_mw_pd
            res["tables"]["clustered_load"] = cl.round(3)
        else:
            res["stats"]["objective_pd"] = float(ncd.objective)
            res["stats"]["objective_pop"] = float(ncp.objective)
            res["stats"]["objective_delta_pct"] = _rel_pct(float(ncp.objective), float(ncd.objective))
            # determinism bound: a replica of the variant (same config, other
            # run name) shows how much of the delta could be solver noise
            prep = WF / f"results/{REPLICA}/{INTERCONNECT}/networks/{PREPARED}.nc"
            if prep.exists():
                ncr = load_network(prep)
                cap_noise = float(
                    (ncp.generators.p_nom_opt.sort_index() - ncr.generators.p_nom_opt.sort_index()).abs().max(),
                )
                res["stats"]["replica_capacity_noise_mw"] = cap_noise
                res["stats"]["replica_objective_noise_pct"] = _rel_pct(
                    float(ncr.objective),
                    float(ncp.objective),
                )
            cap = {}
            for side, n in (("pd", ncd), ("pop", ncp)):
                caps = []
                for comp in ("generators", "storage_units"):
                    c = getattr(n, comp)
                    if not c.empty and "p_nom_opt" in c:
                        caps.append(c.groupby("carrier")["p_nom_opt"].sum())
                cap[side] = pd.concat(caps) if caps else pd.Series(dtype=float)
            cap_df = pd.DataFrame({"p_nom_opt_pd": cap["pd"], "p_nom_opt_pop": cap["pop"]}).fillna(0.0)
            cap_df["delta_pct"] = (
                100 * (cap_df.p_nom_opt_pop - cap_df.p_nom_opt_pd) / cap_df.p_nom_opt_pd.replace(0, np.nan)
            )
            res["tables"]["capacity_by_carrier"] = cap_df.round(3)

    return res


# --------------------------------------------------------------- report side
def maps_html(res: dict) -> str:
    """Three-panel choropleths (legacy | population | difference) per quantity.

    Reuses ``_plot_choropleth_on_ax`` from workflow/scripts/plot_network_maps
    (show_lines=False makes it network-independent). Region files are
    identical across the two runs (verified topology invariant), so the
    baseline run's geospatial outputs are used for both sides.
    """
    try:
        import cartopy.crs as ccrs
        import geopandas as gpd
        import pypsa
        from matplotlib.colors import Normalize

        sys.path.insert(0, str(WF / "scripts"))
        import plot_network_maps as pnm
    except Exception as e:  # cartopy/geopandas optional at report time
        return f"<p>maps unavailable: {e}</p>"

    geo = WF / f"resources/{BASELINE}/geospatial/{INTERCONNECT}"
    regions_s = gpd.read_file(geo / "regions_onshore_s.geojson")
    regions_c = gpd.read_file(geo / f"regions_onshore_s_{AB_CLUSTERS}.geojson")
    dummy = pypsa.Network()

    def three_panel(regions, vals_pd, vals_pop, title, unit, vmax_q=1.0):
        idx = vals_pd.index.union(vals_pop.index)
        a = vals_pd.reindex(idx, fill_value=0.0).astype(float)
        b = vals_pop.reindex(idx, fill_value=0.0).astype(float)
        diff = b - a
        vmax = float(max(a.quantile(vmax_q), b.quantile(vmax_q), 1e-9))
        dlim = float(max(diff.abs().max(), 1e-9))
        bounds = regions.total_bounds
        lon = float((bounds[0] + bounds[2]) / 2)
        fig, axes = plt.subplots(
            1,
            3,
            subplot_kw={"projection": ccrs.EqualEarth(lon)},
            figsize=(15, 4.8),
        )
        panels = [
            (axes[0], a, "viridis", 0.0, vmax, f"legacy Pd ({BASELINE})"),
            (axes[1], b, "viridis", 0.0, vmax, f"population ({VARIANT})"),
            (axes[2], diff, "RdBu_r", -dlim, dlim, "population \u2212 legacy"),
        ]
        for ax, vals, cmap, vmin_, vmax_, name in panels:
            pnm._plot_choropleth_on_ax(
                dummy,
                vals,
                regions.copy(),
                ax,
                cmap=cmap,
                vmin=vmin_,
                vmax=vmax_,
                show_lines=False,
            )
            ax.set_title(name, fontsize=10)
            sm = plt.cm.ScalarMappable(cmap=cmap, norm=Normalize(vmin_, vmax_))
            fig.colorbar(sm, ax=ax, shrink=0.75, pad=0.02, label=unit)
        fig.suptitle(title, fontsize=12)
        cap = f"{title} — largest per-region shift: {float(diff.abs().max()):,.3g} {unit}" + (
            f"; color scale capped at the {vmax_q:.0%} quantile" if vmax_q < 1.0 else ""
        )
        return _img(fig, cap)

    parts = [
        "<p>Left/middle panels share one color scale; the right panel is the "
        "population-minus-legacy difference on a diverging scale centered at zero. "
        "Gray regions carry no data. Note: polygons are Voronoi cells of the "
        "modeled substations clipped to the <em>western</em> onshore shape; "
        "where the network excludes buses (e.g. the CA-only scope), border "
        "cells absorb the excluded area — spillover is not out-of-area load.</p>",
    ]
    ws = res["weight_share"]
    parts.append(
        three_panel(
            regions_s,
            ws["pd"],
            ws["pop"],
            "Load-weight share per substation (percent of interconnect total)",
            "%",
            vmax_q=0.99,
        ),
    )
    bf = res["bus_frame"]
    parts.append(
        three_panel(
            regions_s,
            bf["mw_pd"],
            bf["mw_pop"],
            "Mean allocated demand per substation",
            "MW",
            vmax_q=0.99,
        ),
    )
    if "clustered_load" in res["tables"]:
        cl = res["tables"]["clustered_load"]
        parts.append(
            three_panel(
                regions_c,
                cl["load_mw_pd"],
                cl["load_mw_pop"],
                f"Mean clustered demand per zone (c{AB_CLUSTERS})",
                "MW",
            ),
        )
    return "\n".join(parts)


def _png(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return base64.b64encode(buf.getvalue()).decode()


def _img(fig, title: str) -> str:
    return (
        f'<figure><img alt="{title}" src="data:image/png;base64,{_png(fig)}"/><figcaption>{title}</figcaption></figure>'
    )


def _tbl(df: pd.DataFrame, caption: str) -> str:
    return f"<h3>{caption}</h3>" + df.to_html(border=0, na_rep="—", float_format=lambda v: f"{v:,.3f}")


def figures(res: dict) -> str:
    df = res["bus_frame"]
    parts = []

    fig, ax = plt.subplots(figsize=(6, 5))
    m = (df.mw_pd > 0) | (df.mw_pop > 0)
    ax.scatter(df.loc[m, "mw_pd"], df.loc[m, "mw_pop"], s=6, alpha=0.4)
    lim = max(df.mw_pd.max(), df.mw_pop.max()) * 1.05
    ax.plot([0, lim], [0, lim], lw=0.8, color="grey")
    ax.set_xlabel("mean bus load, legacy Pd weights (MW)")
    ax.set_ylabel("mean bus load, census population weights (MW)")
    ax.set_title("Per-bus demand allocation, A vs B")
    parts.append(_img(fig, "Per-substation mean load: legacy Pd (x) vs census population (y); grey line = unchanged."))

    fig, ax = plt.subplots(figsize=(7, 3.5))
    zt = res["tables"]["by_zone"]["delta_pct"].sort_values()
    zt.plot.barh(ax=ax)
    ax.set_xlabel("demand change, population vs legacy (%)")
    ax.set_title("Per-ReEDS-zone demand shift")
    parts.append(_img(fig, "Zone-level demand shift (percent, population-based vs legacy)."))

    return "\n".join(parts)


def build_report(res: dict, solve: bool) -> Path:
    inv_rows = "".join(
        f"<tr><td>{i['name']}</td><td class={'ok' if i['ok'] else 'bad'}>{'PASS' if i['ok'] else 'FAIL'}</td>"
        f"<td>{i['detail']}</td></tr>"
        for i in res["invariants"]
    )
    s = res["stats"]
    stat_rows = "".join(
        f"<tr><td>{k}</td><td>{v:,}</td></tr>" if isinstance(v, int) else f"<tr><td>{k}</td><td>{v}</td></tr>"
        for k, v in s.items()
    )
    tables = [
        _tbl(res["tables"]["by_state"], "Demand by state (mean MW, with in-network LAF shares)"),
        _tbl(res["tables"]["by_zone"], "Demand by ReEDS zone"),
        _tbl(res["tables"]["top_bus_movers"], "Top 20 substation-level movers (mean MW)"),
    ]
    if "clustered_load" in res["tables"]:
        tables.append(_tbl(res["tables"]["clustered_load"], f"Clustered ({AB_CLUSTERS}-zone) load by cluster bus"))
    if "capacity_by_carrier" in res["tables"]:
        tables.append(_tbl(res["tables"]["capacity_by_carrier"], "Solved capacity by carrier (p_nom_opt, MW)"))

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>A/B: bus_allocation population vs breakthrough</title>
<style>
 body {{ background:#fff; color:#111; font:14px/1.5 -apple-system, sans-serif; max-width:1100px; margin:2em auto; padding:0 1em; }}
 table {{ border-collapse:collapse; margin:0.5em 0 1.5em; }}
 td, th {{ padding:3px 10px; border-bottom:1px solid #ddd; text-align:right; }}
 td:first-child, th:first-child {{ text-align:left; }}
 .ok {{ color:#0a7d32; font-weight:600; }} .bad {{ color:#b00020; font-weight:600; }}
 figure {{ margin:1.5em 0; }} figcaption {{ color:#555; font-size:12px; }}
 img {{ max-width:100%; }}
</style></head><body>
<h1>A/B report: <code>electricity.demand.bus_allocation</code></h1>
<p>Same branch, same config ({INTERCONNECT}, scope={SCOPE}, c{AB_CLUSTERS}, {OPTS}, {SECTOR}), two runs:
<b>{BASELINE}</b> = legacy Breakthrough <code>Pd</code> weights,
<b>{VARIANT}</b> = 2020 census county-population weights.
Solve stage {"included" if solve else "skipped"}.</p>
<h2>Invariants</h2>
<table><tr><th>check</th><th>verdict</th><th>detail</th></tr>{inv_rows}</table>
<h2>Headline numbers</h2>
<table>{stat_rows}</table>
<h2>Figures</h2>
{figures(res)}
<h2>Maps</h2>
{maps_html(res)}
<h2>Tables</h2>
{"".join(tables)}
<p><small>Generated by tests/equivalence/ab.py on {time.strftime("%Y-%m-%d %H:%M:%S")}.</small></p>
</body></html>"""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"{REPORT_STEM}.html"
    out.write_text(html)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-solve", action="store_true")
    ap.add_argument("--skip-build", action="store_true", help="analyze/report existing artifacts only")
    ap.add_argument(
        "--replica",
        action="store_true",
        help="also solve an identical-config replica of the variant to bound solver noise",
    )
    ap.add_argument("--jobs", type=int, default=4)
    ap.add_argument("--scope", choices=tuple(SCOPES), default="ca")
    args = ap.parse_args()
    set_scope(args.scope)
    solve = not args.skip_solve

    if not args.skip_build:
        seed_workflow_configs()
        for run_name, method in sides().items():
            build(run_name, method, solve, args.jobs)
        if args.replica and solve:
            build(REPLICA, "population", solve, args.jobs)

    res = analyze(solve)
    report = build_report(res, solve)

    ok = all(i["ok"] for i in res["invariants"])
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / f"{REPORT_STEM.replace('report', 'findings')}.json").write_text(
        json.dumps(
            {"invariants": res["invariants"], "stats": res["stats"]},
            indent=1,
            default=str,
        ),
    )
    print(f"[ab] invariants: {'PASS' if ok else 'FAIL'}")
    print(f"[ab] report: {report}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
