# modify_base_network: true #modify BE network to calibrate humbodlt TX capacity

osw_config:
  enable_osw: false
  humboldt_capacity: 1607

offshore_shape:
  use: eez #options are ca_osw, eez

offshore_network:
  enable: true # set to true to enable offshore network
  bus_spacing: 25000 # km
