clustering:
  aggregation_strategies:
    generators:
      committable: any
      fuel_cost: mean
      heat_rate: mean
      ramp_limit_down: max
      ramp_limit_up: max
      vom_cost: mean
  cluster_network:
    aggregation_zones: reeds_zone
    algorithm: kmeans
    consider_efficiency_classes: false
    exclude_carriers: []
    feature: solar+onwind-time
  simplify_network:
    algorithm: kmeans
    feature: solar+onwind-time
    to_substations: false
  temporal:
    resolution_elec: false
    resolution_sector: false
conventional:
  dynamic_fuel_price: true
  unit_commitment: false
costs:
  emission_prices:
    co2: 0.0
    co2_monthly_prices: false
    enable: false
  fill_values:
    CO2 intensity: 0
    FOM: 0
    VOM: 0
    discount rate: 0.07
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
  marginal_cost:
    H2: 0.0
    battery: 0.0
    battery inverter: 0.0
    electrolysis: 0.0
    fuel cell: 0.0
    hydro: 0.0
    offwind: 0.0
    onwind: 0.0
    solar: 0.0
  ng_fuel_year: 2019
  rooftop_share: 0.0
  version: v0.6.0
  year: 2030
electricity:
  BAU_mincapacities: 50
  SAFE_regional_reservemargins: config/policy_constraints/SAFE_regional_prm.csv
  SAFE_reservemargin: 0.14
  agg_p_nom_limits: config/policy_constraints/agg_p_nom_minmax.csv
  autarky:
    by_country: false
    enable: false
  co2base: 663500000.0
  co2limit: 663500000.0
  co2limit_enable: true
  conventional_carriers:
  - nuclear
  - oil
  - OCGT
  - CCGT
  - coal
  - egs
  - geothermal
  - biomass
  demand:
    disaggregation: pop
    profile: efs
    scale: 1.36
    scaling_factor_monthly:
    - 1.196442
    - 1.27942
    - 1.361699
    - 1.206554
    - 1.198357
    - 1.04308
    - 1.05757
    - 1.056679
    - 1.002989
    - 1.111066
    - 1.302436
    - 1.367929
    scenario:
      aeo: reference
      efs_case: reference
      efs_speed: moderate
  extendable_carriers:
    Generator:
    - solar
    - onwind
    - offwind
    - offwind_floating
    - OCGT
    - CCGT
    - coal
    - egs
    Link: []
    StorageUnit:
    - 4hr_battery_storage
    Store: []
  gaslimit: false
  gaslimit_enable: false
  geothermal:
    egs: true
    egs_reduction: 0.9
    egs_sc_file: new_geo_egs_supply_curve.geojson
    storage: false
  max_hours:
    H2: 168
    battery: 6
  operational_reserve:
    activate: false
    contingency: 4000
    epsilon_load: 0.02
    epsilon_vres: 0.02
  portfolio_standards: config/policy_constraints/portfolio_standards.csv
  psh:
    sc_file: 40-100-dam-height-10hr-no-croplands-no-ephemeral-no-highways.gpkg
  regional_Co2_limits: config/policy_constraints/regional_Co2_limits.csv
  renewable_carriers:
  - onwind
  - offwind
  - offwind_floating
  - solar
  - hydro
  retirement: economic
  transmission_interface_limits: config/policy_constraints/transmission_interface_limits.csv
  voltage_simplified: 230
enable:
  allow_new_plant: true
  build_cutout: false
focus_weights: null
foresight: null
lines:
  interface_transmission_limits: true
  length_factor: 1.25
  max_extension: 1000000.0
  s_max_pu: 0.7
  s_nom_max: .inf
  types:
    115.0: Al/St 240/40 2-bundle 220.0
    138.0: Al/St 240/40 2-bundle 220.0
    161.0: Al/St 240/40 2-bundle 220.0
    230.0: Al/St 240/40 2-bundle 220.0
    345.0: Al/St 240/40 4-bundle 380.0
    500.0: Al/St 560/50 4-bundle 750.0
    765.0: Al/St 560/50 4-bundle 750.0
links:
  max_extension: 1000000.0
  p_max_pu: 1.0
  p_nom_max: .inf
run:
  disable_progressbar: false
  name: geo_2019
  shared_cutouts: true
  shared_resources: true
  validation: false
scenario:
  clusters:
  - 10
  interconnect:
  - texas
  ll:
  - v2
  opts: Ep-Co2L1-egsR0.9
  planning_horizons:
  - 2030
  scope: total
  sector: ''
sector:
  co2_sequestration_potential: 0
  demand:
    disaggregation:
      commercial: pop
      industry: pop
      residential: pop
      transport: pop
    profile:
      commercial: eulp
      industry: efs
      residential: eulp
      transport: efs
    scale:
      commercial: aeo
      industry: aeo
      residential: aeo
      transport: aeo
    scenarios:
      aeo: reference
  heating:
    heat_pump_sink_T: 55.0
  natural_gas:
    allow_imports_exports: true
    cyclic_storage: false
snapshots:
  end: '2020-01-01'
  inclusive: left
  start: '2019-01-01'
solving:
  mem: 30000
  options:
    assign_all_duals: true
    clip_p_max_pu: 0.01
    horizon: 8760
    linearized_unit_commitment: true
    load_shedding: false
    max_iterations: 6
    min_iterations: 4
    noisy_costs: true
    rolling_horizon: false
    seed: 123
    skip_iterations: true
    track_iterations: false
    transmission_losses: 2
  solver:
    name: gurobi
    options: gurobi-default
  solver_options:
    cbc-default: {}
    cplex-default:
      barrier.convergetol: 1.0e-05
      feasopt.tolerance: 1.0e-06
      lpmethod: 4
      solutiontype: 2
      threads: 4
    glpk-default: {}
    gurobi-default:
      AggFill: 0
      BarConvTol: 0.0001
      FeasibilityTol: 1.0e-05
      GURO_PAR_BARDENSETHRESH: 200
      OptimalityTol: 1.0e-05
      PreDual: 0
      Seed: 123
      crossover: 0
      method: 2
      threads: 10
    gurobi-fallback:
      BarConvTol: 1.0e-05
      BarHomogeneous: 1
      FeasibilityTol: 1.0e-05
      OptimalityTol: 1.0e-05
      Seed: 123
      crossover: 0
      method: 2
      name: gurobi
      threads: 8
    gurobi-numeric-focus:
      BarConvTol: 1.0e-05
      BarHomogeneous: 1
      FeasibilityTol: 0.0001
      NumericFocus: 3
      ObjScale: -0.5
      OptimalityTol: 0.0001
      Seed: 123
      crossover: 0
      method: 2
      name: gurobi
      threads: 8
    highs-default:
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      large_matrix_value: 1e9
      parallel: 'on'
      primal_feasibility_tolerance: 1e-5
      random_seed: 123
      run_crossover: 'off'
      small_matrix_value: 1e-6
      solver: ipm
      threads: 4
  walltime: '12:00:00'
texas_specific:
  capacity_ercot: ercot_cap_2024_jul
  replace_uri: true
  texas_reliability: true
