# PyPSA-USA Default Configuration File

run:
  name: "Tutorial" # use this to keep track of runs with different settings
  disable_progressbar: false # set to true to disable the progressbar
  shared_resources: false # set to true to share the default resources across runs
  shared_cutouts: true # set to true to share the default cutout(s) across runs
  validation: false # set to true to run back-casting plots

# docs :
scenario:
  interconnect: [texas] #"usa|texas|western|eastern"
  clusters: [10]
  simpl: [500]
  opts: [RPS-REM-400SEG]
  ll: [v1.0]
  scope: "total" # "urban", "rural", or "total"
  sector: "" # G
  planning_horizons: [2030, 2050]    #(2018-2023, 2030, 2040, 2050)

# docs :
enable:
  build_cutout: false

snapshots:
  start: "2019-01-01"
  end: "2019-02-01"
  inclusive: "left"

# docs :
electricity:
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, geothermal, biomass, waste] # Choose the conventional plant types to include in network
  renewable_carriers: [onwind, offwind, offwind_floating, solar, hydro] # Choose the renewable plant types to include in network
  voltage_simplified: 230 #Voltage level to simplify network to in rule "simplify network"
  co2limit: 1.4728e+9 # 0.8 * 1.841e+9
  co2limit_enable: false # For sector coupled studies
  co2base: 226.86e+6 #base_from_2020 Locations of the 250 MMmt of CO2 emissions from the WECC 2021.
  gaslimit: false # global gas usage limit of X MWh_th
  gaslimit_enable: false # For sector coupled studies
  retirement: economic # "economic" or "technical"
  SAFE_reservemargin: 0.14
  regional_Co2_limits: 'config/policy_constraints/regional_Co2_limits.csv'
  agg_p_nom_limits: 'config/policy_constraints/agg_p_nom_minmax.csv'
  portfolio_standards: 'config/policy_constraints/portfolio_standards.csv'
  SAFE_regional_reservemargins: 'config/policy_constraints/SAFE_regional_prm.csv'
  transmission_interface_limits: 'config/policy_constraints/transmission_interface_limits.csv'

  operational_reserve:
    activate: false
    epsilon_load: 0.02
    epsilon_vres: 0.02
    contingency: 4000

  max_hours:
    battery: 6
    H2: 168

  extendable_carriers:
    Generator: [solar, onwind, offwind, offwind_floating, OCGT, CCGT, coal, nuclear, coal-95CCS, CCGT-95CCS, SMR] #include CCGT-CCS
    StorageUnit: [4hr_battery_storage, 8hr_battery_storage, 8hr_PHS, 10hr_PHS, 12hr_PHS] # [Xhr-battery-storage (2-10 hours)]
    Store: []
    Link: [] 

  demand: 
    profile: efs # efs, eia
    scenario: 
      efs_case: reference # reference, medium, high
      efs_speed: moderate # slow, moderate, rapid
      aeo: reference

# docs :
conventional:
  unit_commitment: false
  dynamic_fuel_price: 
    pudl: true
    wholesale: true

# docs :
lines:
  s_max_pu: 0.7
  s_nom_max: .inf
  max_extension: 2000 #MW
  length_factor: 1.25
  interface_transmission_limits: false
  transport_model: false

# docs :
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  max_extension: 2000 #MW

# docs :
costs:
  atb:
    model_case: "Market" # Market, R&D
    scenario: "Moderate" # Advanced, Conservative, Moderate
  aeo:
    scenario: "reference" # reference, high, low
  social_discount_rate: 0.02
  ng_fuel_year: 2019 # year of the natural gas price from CAISO [2019- 2023]
  emission_prices: # in currency per tonne emission, only used with the option Ep
    enable: false
    co2: 0.
    co2_monthly_prices: false
  ptc_modifier:
    onwind: 27.50
    biomass: 27.50
  itc_modifier:
    solar: 0.3
    offwind: 0.3
    offwind_floating: 0.3
    EGS: 0.3
    geothermal: 0.3
    SMR: 0.3
    nuclear: 0.3
    hydro: 0.3
    4hr_battery_storage: 0.3
    6hr_battery_storage: 0.3
    8hr_battery_storage: 0.3
    8hr_PHS: 0.3
    10hr_PHS: 0.3
    12hr_PHS: 0.3
  max_growth:
    base:
      SMR: 1000
    rate:
      SMR: 1.15
      nuclear: 1.15


# docs :
sector:
  co2_sequestration_potential: 0
  natural_gas:
    allow_imports_exports: true # false to be implemented
    cyclic_storage: false
  heating:
    heat_pump_sink_T: 55.
  demand:
    profile:
      residential: eulp # efs, eulp
      commercial: eulp # efs, eulp
      transport: efs # efs
      industry: efs # efs
    scale:
      residential: aeo # efs, aeo
      commercial: aeo # efs, aeo
      transport: aeo # efs, aeo
      industry: aeo # efs, aeo
    disaggregation: 
      residential: pop # pop
      commercial: pop # pop
      transport: pop # pop
      industry: pop # pop
    scenarios:
      aeo: reference

# docs :
clustering:
  simplify_network:
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time # only for hac. choose from: [solar+onwind-time, solar+onwind-cap, solar-time, solar-cap, solar+offwind-cap] etc.
  cluster_network:
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time
    aggregation_zones: 'reeds_zone' # [balancing_area, state, reeds_zone]
    exclude_carriers: []
    consider_efficiency_classes: false
  aggregation_strategies:
    generators:
      build_year: 'capacity_weighted_average'
      lifetime: 'capacity_weighted_average'
      start_up_cost: 'capacity_weighted_average'
      min_up_time: 'capacity_weighted_average'
      min_down_time: 'capacity_weighted_average'
      ramp_limit_up: max
      ramp_limit_down: max
      committable: any
      vom_cost: mean
      fuel_cost: mean
      heat_rate: mean
  temporal:
    resolution_elec: false
    resolution_sector: false

focus_weights:

# docs :
solving:
  #tmpdir: "path/to/tmp"
  options:
    load_shedding: false
    clip_p_max_pu: 1.e-2
    noisy_costs: true
    skip_iterations: true
    rolling_horizon: false
    seed: 123
    # options that go into the optimize function
    track_iterations: false
    min_iterations: 4
    max_iterations: 6
    transmission_losses: 2
    linearized_unit_commitment: true
    horizon: 8760
    assign_all_duals: true


  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/options/definitions.html#solver
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-4
      OptimalityTol: 1.e-4
      FeasibilityTol: 1.e-3
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
    gurobi-numeric-focus:
      name: gurobi
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      name: gurobi
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  mem: 30000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  walltime: "12:00:00"


# docs :
custom_files:
  activate: false
  files_path: ''
  network_name: ''