plotting:
  costs_max: 800
  costs_threshold: 1

  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.

  tech_colors:
    "onwind": "#235ebc"
    "wind": "#235ebc"
    "onshore wind": "#235ebc"
    'offwind': "#dd6895"
    'offshore wind': "#6895dd"
    'offwind-ac': "#6895dd"
    'offshore wind ac': "#6895dd"
    'offwind-dc': "#74c6f2"
    'offshore wind dc': "#74c6f2"
    'offwind_floating': "#11a1c1"
    "hydro": "#08ad97"
    "hydro+PHS": "#08ad97"
    "PHS": "#08ad97"
    "hydro reservoir": "#08ad97"
    'hydroelectricity': '#08ad97'
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    'solar': "#f9d002"
    'solar PV': "#f9d002"
    'solar thermal': '#ffef60'
    'biomass': '#0c6013'
    'solid biomass': '#06540d'
    'biogas': '#23932d'
    'waste': '#68896b'
    'geothermal': '#ba91b1'
    "OCGT": "#d35050"
    "gas": "#d35050"
    "ng": "#d35050"
    "natural gas": "#d35050"
    "CCGT": "#b20101"
    "nuclear": "#ff9000"
    "coal": "#707070"
    "lignite": "#9e5a01"
    "oil": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#b8ea04"
    "2hr_battery_storage": "#aee000"
    "4hr_battery_storage": "#a4d600"
    "6hr_battery_storage": "#9acc00"
    "8hr_battery_storage": "#90c200"
    "10hr_battery_storage": "#86b800"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "AC-AC": "#70af1d"
    "AC line": "#70af1d"
    "AC": "#70af1d"
    "links": "#8a1caf"
    "HVDC links": "#8a1caf"
    "DC-DC": "#8a1caf"
    "DC link": "#8a1caf"
    "DC": "#8a1caf"
    "Load": "#2ad55f"
    "res-elec": "#f9d002"
    "res-heat": "#E79CA2"
    "res-cool": "#9CE7E2"
    "com-elec": "#f9d002"
    "com-heat": "#E79CA2"
    "com-cool": "#9CE7E2"
    "ind-elec": "#f9d002"
    "ind-heat": "#E79CA2"
    "trn-elec": "#f9d002"
    "coal-95CCS": "#4b4b4b"
    "coal-99CCS": "#2e2e2e"
    "coal-95CC": "#4b4b4b"
    "coal-99CC": "#2e2e2e"
    "SMR": "#ff5733"
    "CCGT-95CCS": "#800000"
    "CCGT-95CC": "#800000"
    "8hr_PHS": "#069686"
    "10hr_PHS": "#058a79"
    "12hr_PHS": "#047d6c"    
    "8hr_PHS_discharger": "#069686"
    "10hr_PHS_discharger": "#058a79"
    "12hr_PHS_discharger": "#047d6c"
    "8hr_PHS_charger": "#069686"
    "10hr_PHS_charger": "#058a79"
    "12hr_PHS_charger": "#047d6c"  
    "hydrogen_ct": "#ea048a"
    "demand_response": "#8c03fc"
    "dac": "#4c004c"

    # sector studies only 

    lpg: "#70217b"
    ch4: "#539307"
    co2: "#cd7e0d"

    res-elec: "#f9d002"
    res-total-elec: "#f9d002"
    res-urban-elec: "#f9d002"
    res-rural-elec: "#f9d002"
    res-heat: "#E79CA2"
    res-total-heat: "#E79CA2"
    res-urban-heat: "#E79CA2"
    res-rural-heat: "#E79CA2"
    res-cool: "#9CE7E2"
    res-total-cool: "#9CE7E2"
    res-urban-cool: "#9CE7E2"
    res-rural-cool: "#9CE7E2"

    com-elec: "#f9d002"
    com-total-elec: "#f9d002"
    com-urban-elec: "#f9d002"
    com-rural-elec: "#f9d002"
    com-heat: "#E79CA2"
    com-total-heat: "#E79CA2"
    com-urban-heat: "#E79CA2"
    com-rural-heat: "#E79CA2"
    com-cool: "#9CE7E2"
    com-total-cool: "#9CE7E2"
    com-urban-cool: "#9CE7E2"
    com-rural-cool: "#9CE7E2"

    ind-elec: "#f9d002"
    ind-heat: "#E79CA2"
    trn-elec: "#f9d002"

    "gas storage": "#f69d09"
    "gas pipeline": "#f69d09"
    "gas trade": "ae3dc2"
    "gas production": "#d35050"

    trn-veh: "#0a0100"
    trn-veh-lgt: "#0a0100"
    trn-veh-med: "#0a0100"
    trn-veh-hvy: "#0a0100"
    trn-veh-bus: "#0a0100"

    trn-elec-veh: "#0a0100"
    trn-elec-veh-lgt: "#2BAAD4"
    trn-elec-veh-med: "#2FD085"
    trn-elec-veh-hvy: "#6DCD32"
    trn-elec-veh-bus: "#d3d32c"
    trn-lpg: "#0a0100"
    trn-lpg-veh: "#0a0100"
    trn-lpg-veh-lgt: "#D4552B"
    trn-lpg-veh-med: "#D02F7A"
    trn-lpg-veh-hvy: "#9232CD"
    trn-lpg-veh-bus: "#2C2CD3"

    trn-rail: "#0a0100"
    trn-lpg-rail: "#0a0100"
    trn-lpg-rail-psg: "#9F9160"
    trn-lpg-rail-ship: "#606E9F"

    trn-air: "#0a0100"
    trn-lpg-air: "#0a0100"
    trn-lpg-air-psg: "#A45B75"

    trn-boat: "#0a0100"
    trn-lpg-boat: "#0a0100"
    trn-lpg-boat-ship: "#5BA48A"

    res-space-heat: "#F10E1B"
    com-space-heat: "#F10E1B"
    res-water-heat: "#F10E1B"
    com-water-heat: "#F10E1B"
    res-rural-cool: "#196CE6"
    com-rural-cool: "#196CE6"
    res-urban-cool: "#196CE6"
    com-urban-cool: "#196CE6"
    res-total-cool: "#196CE6"
    com-total-cool: "#196CE6"
    res-rural-space-heat: "#F10E1B"
    com-rural-space-heat: "#F10E1B"
    res-urban-space-heat: "#F10E1B"
    com-urban-space-heat: "#F10E1B"
    res-total-space-heat: "#F10E1B"
    com-total-space-heat: "#F10E1B"
    res-rural-water-heat: "#E817C3"
    com-rural-water-heat: "#E817C3"
    res-urban-water-heat: "#E817C3"
    com-urban-water-heat: "#E817C3"
    res-total-water-heat: "#E817C3"
    com-total-water-heat: "#E817C3"
    res-rural-air-con: "#3B98C4"
    com-rural-air-con: "#3B98C4"
    res-urban-air-con: "#3B98C4"
    com-urban-air-con: "#3B98C4"
    res-total-air-con: "#3B98C4"
    com-total-air-con: "#3B98C4"
    res-rural-gas-furnace: "#F68D09"
    com-rural-gas-furnace: "#F68D09"
    res-urban-gas-furnace: "#F68D09"
    com-urban-gas-furnace: "#F68D09"
    res-total-gas-furnace: "#F68D09"
    com-total-gas-furnace: "#F68D09"
    res-rural-space-gas-furnace: "#F68D09"
    com-rural-space-gas-furnace: "#F68D09"
    res-urban-space-gas-furnace: "#F68D09"
    com-urban-space-gas-furnace: "#F68D09"
    res-total-space-gas-furnace: "#F68D09"
    com-total-space-gas-furnace: "#F68D09"
    res-rural-oil-furnace: "#006B88"
    com-rural-oil-furnace: "#006B88"
    res-urban-oil-furnace: "#006B88"
    com-urban-oil-furnace: "#006B88"
    res-total-oil-furnace: "#006B88"
    com-total-oil-furnace: "#006B88"
    res-rural-space-oil-furnace: "#006B88"
    com-rural-space-oil-furnace: "#006B88"
    com-urban-space-oil-furnace: "#006B88"
    res-urban-space-oil-furnace: "#006B88"
    com-total-space-oil-furnace: "#006B88"
    res-total-space-oil-furnace: "#006B88"
    res-rural-elec-furnace: "#DCEC13"
    com-rural-elec-furnace: "#DCEC13"
    res-urban-elec-furnace: "#DCEC13"
    com-urban-elec-furnace: "#DCEC13"
    res-total-elec-furnace: "#DCEC13"
    com-total-elec-furnace: "#DCEC13"
    res-rural-space-elec-furnace: "#DCEC13"
    com-rural-space-elec-furnace: "#DCEC13"
    com-urban-space-elec-furnace: "#DCEC13"
    res-urban-space-elec-furnace: "#DCEC13"
    com-total-space-elec-furnace: "#DCEC13"
    res-total-space-elec-furnace: "#DCEC13"
    res-rural-water-gas: "#D87627"
    com-rural-water-gas: "#D87627"
    res-urban-water-gas: "#D87627"
    com-urban-water-gas: "#D87627"
    res-total-water-gas: "#D87627"
    com-total-water-gas: "#D87627"
    res-rural-water-oil: "#774115"
    com-rural-water-oil: "#774115"
    res-urban-water-oil: "#774115"
    com-urban-water-oil: "#774115"
    res-total-water-oil: "#774115"
    com-total-water-oil: "#774115"
    res-rural-water-elec: "#5CDC23"
    com-rural-water-elec: "#5CDC23"
    res-urban-water-elec: "#5CDC23"
    com-urban-water-elec: "#5CDC23"
    res-total-water-elec: "#5CDC23"
    com-total-water-elec: "#5CDC23"
    res-rural-ashp: "#E14C1E"
    com-rural-ashp: "#E14C1E"
    res-urban-ashp: "#E14C1E"
    com-urban-ashp: "#E14C1E"
    res-total-ashp: "#E14C1E"
    com-total-ashp: "#E14C1E"
    res-rural-gshp: "#D926A6"
    com-rural-gshp: "#D926A6"
    res-urban-gshp: "#D926A6"
    com-urban-gshp: "#D926A6"
    res-total-gshp: "#D926A6"
    com-total-gshp: "#D926A6"
    res-rural-space-heat-store: "#3096CF"
    com-rural-space-heat-store: "#3096CF"
    res-urban-space-heat-store: "#3096CF"
    com-urban-space-heat-store: "#3096CF"
    res-total-space-heat-store: "#3096CF"
    com-total-space-heat-store: "#3096CF"
    res-elec-infra: "#9CD926"
    com-elec-infra: "#9CD926"

    ind-coal-furnace: "#EC13B4"
    ind-heat-pump: "#E83E17"
    ind-gas-furnace: "#E0AE1F"
    ind-elec-infra: "#9CD926"

    res-total-elec-dr: "#45ba75"
    res-urban-elec-dr: "#45ba75"
    res-rural-elec-dr: "#45ba75"
    res-total-heat-dr: "#BA458A"
    res-urban-heat-dr: "#BA458A"
    res-rural-heat-dr: "#BA458A"
    res-total-space-heat-dr: "#A55A80"
    res-urban-space-heat-dr: "#A55A80"
    res-rural-space-heat-dr: "#A55A80"
    res-total-water-heat-dr: "#A844BB"
    res-urban-water-heat-dr: "#A844BB"
    res-rural-water-heat-dr: "#A844BB"
    res-total-cool-dr: "#4692B9"
    res-urban-cool-dr: "#4692B9"
    res-rural-cool-dr: "#4692B9"

    com-total-elec-dr: "#45ba75"
    com-urban-elec-dr: "#45ba75"
    com-rural-elec-dr: "#45ba75"
    com-total-heat-dr: "#BA458A"
    com-urban-heat-dr: "#BA458A"
    com-rural-heat-dr: "#BA458A"
    com-total-space-heat-dr: "#A55A80"
    com-urban-space-heat-dr: "#A55A80"
    com-rural-space-heat-dr: "#A55A80"
    com-total-water-heat-dr: "#A844BB"
    com-urban-water-heat-dr: "#A844BB"
    com-rural-water-heat-dr: "#A844BB"
    com-total-cool-dr: "#4692B9"
    com-urban-cool-dr: "#4692B9"
    com-rural-cool-dr: "#4692B9"

    ind-elec-dr: "#45ba75"
    ind-heat-dr: "#BA458A"

    trn-elec-dr: "#45ba75"
    trn-elec-veh-dr: "#45ba75"

  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind: "Fixed Bottom Offshore Wind"
    offwind_floating: "Floating Offshore Wind"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    Load: "Load Shed"
    hydrogen_ct: "Hydrogen Combustion Turbine"
    demand_response: "Demand Response"
    dac: "Direct Air Capture"

    # sector studies only 

    lpg: "Motor Oil"
    ch4: "Methane"
    co2: "Carbon Dioxide"

    res-elec: "Residential Electrical"
    res-total-elec: "Residential Electrical"
    res-urban-elec: "Residential Urban Electrical"
    res-rural-elec: "Residential Rural Electrical"
    res-heat: "Residential Heating"
    res-total-heat: "Residential Heating"
    res-urban-heat: "Residential Urban Heating"
    res-rural-heat: "Residential Rural Heating"
    res-cool: "Residential Cooling"
    res-total-cool: "Residential Cooling"
    res-urban-cool: "Residential Urban Cooling"
    res-rural-cool: "Residential Rural Cooling"

    com-elec: "Commercial Electrical"
    com-total-elec: "Commercial Electrical"
    com-urban-elec: "Commercial Electrical"
    com-rural-elec: "Commercial Electrical"
    com-heat: "Commercial Heating"
    com-total-heat: "Commercial Heating"
    com-urban-heat: "Commercial Urban Heating"
    com-rural-heat: "Commercial Rural Heating"
    com-cool: "Commercial Cooling"
    com-total-cool: "Commercial Cooling"
    com-urban-cool: "Commercial Urban Cooling"
    com-rural-cool: "Commercial Rural Cooling"

    ind-elec: "Industrial Electrical"
    ind-heat: "Industrial Heating"
    trn-elec: "Transportation Electrical"

    "gas storage": "Natural Gas Storage"
    "gas pipeline": "Natural Gas Pipeline"
    "gas trade": "Natural Gas Trading"
    "gas production": "Natural Gas Production"

    trn-veh: "Vehicles"
    trn-veh-lgt: "Light-Duty Vehicles"
    trn-veh-med: "Medium-Duty Vehicles"
    trn-veh-hvy: "Heavy-Duty Vehicles"
    trn-veh-bus: "Buses"

    trn-elec-veh: "Electric Vehicles"
    trn-elec-veh-lgt: "Light Duty EV"
    trn-elec-veh-med: "Medium Duty EV"
    trn-elec-veh-hvy: "Heavy Duty EV"
    trn-elec-veh-bus: "Electric Bus"
    trn-lpg: "Transportaion Gas"
    trn-lpg-veh: "Gas Vehicles"
    trn-lpg-veh-lgt: "Light Duty ICE"
    trn-lpg-veh-med: "Medium Duty ICE"
    trn-lpg-veh-hvy: "Heavy Duty ICE"
    trn-lpg-veh-bus: "Gas Bus"

    trn-rail: "Rail"
    trn-lpg-rail: "Rail Oil"
    trn-lpg-rail-psg: "Passenger Rail Gas"
    trn-lpg-rail-ship: "Shipping Rail Gas"

    trn-air: "Airplane"
    trn-lpg-air: "Airplane Gas"
    trn-lpg-air-psg: "Passenger Air Gas"

    trn-boat: "Marine Shipping Gas"
    trn-lpg-boat: "Domestic Marine Shipping Gas"
    trn-lpg-boat-ship: "Domestic Marine Shipping Gas"

    res-space-heat: "Space Heat"
    com-space-heat: "Space Heat"
    res-water-heat: "Water Heat"
    com-water-heat: "Water Heat"
    res-rural-cool: "Cool"
    com-rural-cool: "Cool"
    res-urban-cool: "Cool"
    com-urban-cool: "Cool"
    res-total-cool: "Cool"
    com-total-cool: "Cool"
    res-rural-space-heat: "Space Heat"
    com-rural-space-heat: "Space Heat"
    res-urban-space-heat: "Space Heat"
    com-urban-space-heat: "Space Heat"
    res-total-space-heat: "Space Heat"
    com-total-space-heat: "Space Heat"
    res-rural-water-heat: "Water Heat"
    com-rural-water-heat: "Water Heat"
    res-urban-water-heat: "Water Heat"
    com-urban-water-heat: "Water Heat"
    res-total-water-heat: "Water Heat"
    com-total-water-heat: "Water Heat"
    res-rural-air-con: "Air Conditioner"
    com-rural-air-con: "Air Conditioner"
    res-urban-air-con: "Air Conditioner"
    com-urban-air-con: "Air Conditioner"
    res-total-air-con: "Air Conditioner"
    com-total-air-con: "Air Conditioner"
    res-rural-gas-furnace: "Gas Furnace"
    com-rural-gas-furnace: "Gas Furnace"
    res-urban-gas-furnace: "Gas Furnace"
    com-urban-gas-furnace: "Gas Furnace"
    res-total-gas-furnace: "Gas Furnace"
    com-total-gas-furnace: "Gas Furnace"
    res-rural-space-gas-furnace: "Gas Furnace"
    com-rural-space-gas-furnace: "Gas Furnace"
    res-urban-space-gas-furnace: "Gas Furnace"
    com-urban-space-gas-furnace: "Gas Furnace"
    res-total-space-gas-furnace: "Gas Furnace"
    com-total-space-gas-furnace: "Gas Furnace"
    res-rural-oil-furnace: "Oil Furnace"
    com-rural-oil-furnace: "Oil Furnace"
    res-urban-oil-furnace: "Oil Furnace"
    com-urban-oil-furnace: "Oil Furnace"
    res-total-oil-furnace: "Oil Furnace"
    com-total-oil-furnace: "Oil Furnace"
    res-rural-space-oil-furnace: "Oil Furnace"
    com-rural-space-oil-furnace: "Oil Furnace"
    com-urban-space-oil-furnace: "Oil Furnace"
    res-urban-space-oil-furnace: "Oil Furnace"
    com-total-space-oil-furnace: "Oil Furnace"
    res-total-space-oil-furnace: "Oil Furnace"
    res-rural-elec-furnace: "Electric Furnace"
    com-rural-elec-furnace: "Electric Furnace"
    res-urban-elec-furnace: "Electric Furnace"
    com-urban-elec-furnace: "Electric Furnace"
    res-total-elec-furnace: "Electric Furnace"
    com-total-elec-furnace: "Electric Furnace"
    res-rural-space-elec-furnace: "Electric Furnace"
    com-rural-space-elec-furnace: "Electric Furnace"
    com-urban-space-elec-furnace: "Electric Furnace"
    res-urban-space-elec-furnace: "Electric Furnace"
    com-total-space-elec-furnace: "Electric Furnace"
    res-total-space-elec-furnace: "Electric Furnace"
    res-rural-water-gas: "Gas Water Heater"
    com-rural-water-gas: "Gas Water Heater"
    res-urban-water-gas: "Gas Water Heater"
    com-urban-water-gas: "Gas Water Heater"
    res-total-water-gas: "Gas Water Heater"
    com-total-water-gas: "Gas Water Heater"
    res-rural-water-oil: "Oil Water Heater"
    com-rural-water-oil: "Oil Water Heater"
    res-urban-water-oil: "Oil Water Heater"
    com-urban-water-oil: "Oil Water Heater"
    res-total-water-oil: "Oil Water Heater"
    com-total-water-oil: "Oil Water Heater"
    res-rural-water-elec: "Electric Water Heater"
    com-rural-water-elec: "Electric Water Heater"
    res-urban-water-elec: "Electric Water Heater"
    com-urban-water-elec: "Electric Water Heater"
    res-total-water-elec: "Electric Water Heater"
    com-total-water-elec: "Electric Water Heater"
    res-rural-ashp: "Air Source Heat Pump"
    com-rural-ashp: "Air Source Heat Pump"
    res-urban-ashp: "Air Source Heat Pump"
    com-urban-ashp: "Air Source Heat Pump"
    res-total-ashp: "Air Source Heat Pump"
    com-total-ashp: "Air Source Heat Pump"
    res-rural-gshp: "Ground Source Heat Pump"
    com-rural-gshp: "Ground Source Heat Pump"
    res-urban-gshp: "Ground Source Heat Pump"
    com-urban-gshp: "Ground Source Heat Pump"
    res-total-gshp: "Ground Source Heat Pump"
    com-total-gshp: "Ground Source Heat Pump"
    res-rural-space-heat-store: "Building Insulation"
    com-rural-space-heat-store: "Building Insulation"
    res-urban-space-heat-store: "Building Insulation"
    com-urban-space-heat-store: "Building Insulation"
    res-total-space-heat-store: "Building Insulation"
    com-total-space-heat-store: "Building Insulation"
    res-elec-infra: "Electric Distribution"
    com-elec-infra: "Electric Distribution"

    ind-coal-furnace: "Coal furnace"
    ind-heat-pump: "Heat Pump"
    ind-gas-furnace: "Gas Furnace"
    ind-elec-infra: "Electric Distribution"

    res-total-elec-dr: Electric Demand Response 
    res-urban-elec-dr: Urban Electric Demand Response 
    res-rural-elec-dr: Rural Electric Demand Response 
    res-total-heat-dr: Heating Demand Response 
    res-urban-heat-dr: Urban Heating Demand Response 
    res-rural-heat-dr: Rural Heating Demand Response 
    res-total-space-heat-dr: Space Heating Demand Response 
    res-urban-space-heat-dr: Urban Space Heating Demand Response 
    res-rural-space-heat-dr: Rural Space Heating Demand Response 
    res-total-water-heat-dr: Water Heating Demand Response 
    res-urban-water-heat-dr: Urban Water Heating Demand Response 
    res-rural-water-heat-dr: Rural Water Heating Demand Response 
    res-total-cool-dr: Cooling Demand Response 
    res-urban-cool-dr: Urban Cooling Demand Response 
    res-rural-cool-dr: Rural Cooling Demand Response 

    com-total-elec-dr: Electric Demand Response 
    com-urban-elec-dr: Urban Electric Demand Response 
    com-rural-elec-dr: Rural Electric Demand Response 
    com-total-heat-dr: Heating Demand Response 
    com-urban-heat-dr: Urban Heating Demand Response 
    com-rural-heat-dr: Rural Heating Demand Response 
    com-total-space-heat-dr: Space Heating Demand Response 
    com-urban-space-heat-dr: Urban Space Heating Demand Response 
    com-rural-space-heat-dr: Rural Space Heating Demand Response 
    com-total-water-heat-dr: Water Heating Demand Response 
    com-urban-water-heat-dr: Urban Water Heating Demand Response 
    com-rural-water-heat-dr: Rural Water Heating Demand Response 
    com-total-cool-dr: Cooling Demand Response 
    com-urban-cool-dr: Urban Cooling Demand Response 
    com-rural-cool-dr: Rural Cooling Demand Response 

    ind-elec-dr: Electric Demand Response 
    ind-heat-dr: Heating Demand Response 

    trn-elec-dr: Electric Demand Response 
    trn-elec-veh-dr: Electric Demand Response 
