# PyPSA-USA Default Configuration File for developing and testing county transmission network from Reeds
run:
  name: "Default" # use this to keep track of runs with different settings
  disable_progressbar: false # set to true to disable the progressbar
  shared_resources: false # set to true to share the default resources across runs
  shared_cutouts: true # set to true to share the default cutout(s) across runs
  validation: false # set to true to run back-casting plots

# docs :
scenario:
  interconnect: [western] #"usa|texas|western|eastern"
  clusters: [33]
  simpl: [75]
  opts: [REM-3h]
  ll: [v1.0]
  sector: "" # G
  planning_horizons: [2030, 2040, 2050]    #(2018-2023, 2030, 2040, 2050)
foresight:  'perfect' # myopic, perfect

model_topology:
  transmission_network: 'reeds' # [reeds, tamu]
  topological_boundaries: 'reeds_zone' # [county, reeds_zone]
  interface_transmission_limits: false
  include: # mixed zone types not supported
    # reeds_zone: []
    # reeds_state: ['CA']
    # reeds_ba: []
  aggregate: # eligible keys: [reeds_zone, trans_reg]
    # trans_grp: []
    # reeds_zone: []


# docs :
enable:
  build_cutout: false

renewable_weather_years: [2019]

snapshots:
  start: "2019-01-01"
  end: "2020-01-01"
  inclusive: "left"

# docs :
electricity:
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, geothermal, biomass, waste] # Choose the conventional plant types to include in network
  renewable_carriers: [onwind, offwind_floating, solar, hydro] # Choose the renewable plant types to include in network
  retirement: economic # "economic" or "technical"
  SAFE_reservemargin: 0.14
  regional_Co2_limits: 'config/policy_constraints/regional_Co2_limits.csv'
  technology_capacity_targets: 'config/policy_constraints/technology_capacity_targets.csv'
  portfolio_standards: 'config/policy_constraints/portfolio_standards.csv'
  SAFE_regional_reservemargins: 'config/policy_constraints/SAFE_regional_prm.csv'
  transmission_interface_limits: 'config/policy_constraints/transmission_interface_limits.csv'

  operational_reserve:
    activate: false
    epsilon_load: 0.02
    epsilon_vres: 0.02
    contingency: 4000

  extendable_carriers:
    Generator: [solar, onwind, offwind_floating, OCGT, CCGT, CCGT-95CCS, coal, nuclear, hydrogen_ct] #include CCGT-CCS
    StorageUnit: [4hr_battery_storage, 8hr_battery_storage] # [Xhr-battery-storage (2-10 hours)]
    Store: []
    Link: [] 

  demand: 
    profile: efs # efs, eia
    scenario: 
      efs_case: reference # reference, medium, high
      efs_speed: moderate # slow, moderate, rapid
      aeo: reference

  demand_response:
    shift: 0
    marginal_cost: 999999

# docs :
conventional:
  unit_commitment: false
  must_run: false
  dynamic_fuel_price:
    enable: false
    pudl: true
    wholesale: true

# docs :
lines:
  s_max_pu: 0.7
  s_nom_max: .inf
  max_extension: 20000 #MW
  length_factor: 1.25

# docs :
links:
  p_max_pu: 1.0
  p_nom_max: .inf
  max_extension: 20000 #MW

# docs :
co2:
  storage: false   # [false, true]
  network:
    enable: false   # [false, true]
    capital_cost: 2736000   # in USD (cost based on EPA estimation, which assumes a 12-inch diameter and a cost of $228000 per inch for each mile of CO2 pipeline built)
    marginal_cost: 4   # in USD (average cost based on NETL estimation, which ranges between $2 and $6 to transport one tonne of captured CO2)
    lifetime: 40   # in years (average lifetime based on NETL estimation, which ranges between 30 and 50 years)
    discount_rate: 0.07   # in percentage

# docs :
dac:
  enable: false   # [false, true]
  granularity: "node"   # ["node", "state", "nation"] (note: "nation" is not applicable for a network based on sectors - it will default to "node" in this case)
  capital_cost: 6000000   # in USD (cost based on Danish Energy Agency estimation to capture one tonne of CO2 per hour)   # TODO: check this and adapt it to the USA context
  electricity_input: 2.5   # in MWh (average consumption based on https://doi.org/10.1557/s43581-024-00091-5, which ranges between 2 to 3 MWh to capture one tonne of CO2 using electricity only - no heat)
  lifetime: 20   # in years
  discount_rate: 0.07   # in percentage

# docs :
costs:
  atb:
    model_case: "Market" # Market, R&D
    scenario: "Moderate" # Advanced, Conservative, Moderate
  aeo:
    scenario: "reference" # reference, high, low
  social_discount_rate: 0.02
  ng_fuel_year: 2019 # year of the natural gas price from CAISO [2019- 2023]
  emission_prices: # in currency per tonne emission, only used with the option Ep
    enable: false
    co2: 0.
    co2_monthly_prices: false
  ptc_modifier:
    onwind: 27.50
    biomass: 27.50
  itc_modifier:
    solar: 0.3
    offwind: 0.3
    offwind_floating: 0.3
    EGS: 0.3
    geothermal: 0.3
    SMR: 0.3
    nuclear: 0.3
    hydro: 0.3
    2hr_battery_storage: 0.3
    4hr_battery_storage: 0.3
    6hr_battery_storage: 0.3
    8hr_battery_storage: 0.3
    10hr_battery_storage: 0.3
    8hr_PHS: 0.3
    10hr_PHS: 0.3
    12hr_PHS: 0.3
  min_year: # {carrier: year}
    hydrogen_ct: 2040
  max_growth: # {carrier: {base:, rate:}}

# docs :
clustering:
  simplify_network:
    weighting_strategy: demand-capacity # choose from: [population, demand-capacity]
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time # only for hac. choose from: [solar+onwind-time, solar+onwind-cap, solar-time, solar-cap, solar+offwind-cap] etc.
  cluster_network:
    weighting_strategy: demand-capacity # choose from: [population, demand-capacity]
    algorithm: kmeans # choose from: [hac, kmeans]
    feature: solar+onwind-time
    exclude_carriers: []
    consider_efficiency_classes: false
  aggregation_strategies:
    generators:
      build_year: 'capacity_weighted_average'
      lifetime: 'capacity_weighted_average'
      start_up_cost: 'capacity_weighted_average'
      min_up_time: 'capacity_weighted_average'
      min_down_time: 'capacity_weighted_average'
      ramp_limit_up: max
      ramp_limit_down: max
      committable: any
      vom_cost: mean
      fuel_cost: mean
      heat_rate: mean
  temporal:
    resolution_elec: false
    resolution_sector: false

focus_weights:

# docs :
solving:
  #tmpdir: "path/to/tmp"
  options:
    load_shedding: false
    clip_p_max_pu: 1.e-2
    noisy_costs: true
    skip_iterations: true
    rolling_horizon: false
    seed: 123
    # options that go into the optimize function
    track_iterations: false
    min_iterations: 4
    max_iterations: 6
    transmission_losses: 2
    linearized_unit_commitment: true
    horizon: 8760
    assign_all_duals: true


  solver:
    name: gurobi
    options: gurobi-default

  solver_options:
    highs-default:
      # refer to https://ergo-code.github.io/HiGHS/options/definitions.html#solver
      threads: 4
      solver: "ipm"
      run_crossover: "off"
      small_matrix_value: 1e-6
      large_matrix_value: 1e9
      primal_feasibility_tolerance: 1e-5
      dual_feasibility_tolerance: 1e-5
      ipm_optimality_tolerance: 1e-4
      parallel: "on"
      random_seed: 123
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      OptimalityTol: 1.e-4
      FeasibilityTol: 1.e-3
      ScaleFlag: 1
      Seed: 123
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
    gurobi-numeric-focus:
      name: gurobi
      NumericFocus: 3       # Favour numeric stability over speed
      method: 2             # barrier
      crossover: 0          # do not use crossover
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-4
      OptimalityTol: 1.e-4
      ObjScale: -0.5
      threads: 8
      Seed: 123
    gurobi-fallback:        # Use gurobi defaults
      name: gurobi
      crossover: 0
      method: 2             # barrier
      BarHomogeneous: 1     # Use homogeneous barrier if standard does not converge
      BarConvTol: 1.e-5
      FeasibilityTol: 1.e-5
      OptimalityTol: 1.e-5
      Seed: 123
      threads: 8
    cplex-default:
      threads: 4
      lpmethod: 4 # barrier
      solutiontype: 2 # non basic solution, ie no crossover
      barrier.convergetol: 1.e-5
      feasopt.tolerance: 1.e-6
    cbc-default: {} # Used in CI
    glpk-default: {} # Used in CI

  mem: 30000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  walltime: "12:00:00"


# docs :
custom_files:
  activate: false
  files_path: ''
  network_name: ''
