__default__:
  account: iazevedo
  partition: serc
  email: ktehranchi@stanford.edu
  walltime: 00:30:00   # time limit for each job
  cpus_per_task: 1   # number of cores per job
  chdir: $GROUP_HOME/kamran/pypsa-usa/workflow
  output: logs/{rule}/log-%j.out
  error: logs/{rule}/errlog-%j.err

build_renewable_profiles:
  walltime: 06:00:00

add_electricity:
  walltime: 06:00:00

simplify_network:
  walltime: 09:00:00

cluster_network:
  walltime: 09:00:00

solve_network:
  walltime: '24:00:00'

solve_network_validation:
  walltime: 09:00:00

add_demand:
  walltime: 02:00:00
