name: pypsa-usa
channels:
- conda-forge
- bioconda

dependencies:
- python>=3.8
- pip

- pypsa>=0.26.1
- atlite>=0.2.9
- linopy

- dask==2023.7.0
- dask-core==2023.7.0

# Dependencies of the workflow itself
- pandas>=2.1
- xarray>=2023.11.0
- xlrd==2.0.1
- openpyxl==3.1.2
- pycountry==22.3.5
- seaborn==0.12.2
- snakemake-minimal==7.32.4
- memory_profiler==0.61.0
- yaml==0.2.5
- pytables==3.9.1
- lxml==4.9.3
- numpy==1.26.0
- netcdf4==1.6.4
- networkx==3.1
- scipy==1.11.3
- shapely==2.0.2
- progressbar2==4.3.2
- matplotlib==3.8.0
- plotly==5.17.0
- graphviz
- powerplantmatching

# Keep in conda environment when calling ipython
- ipython==8.16.1
- jupyter==1.0.0
- notebook==7.0.6
- ipykernel==6.25.2

# GIS dependencies:
- geopy==2.4.0
- cartopy==0.22.0
- descartes==1.1.0
- rasterio==1.3.8
- geopandas>=0.11.0
- geopandas-base==0.14.0

# TODO: check these dependencies
- tqdm==4.66.1
- pytz==2023.3.post1
- country_converter==1.0.0
- tabula-py==2.7.0
- fs==2.4.11

- pip:
  - vresutils==0.3.1
  - tsam>=1.1.0
  - gurobipy==10.0.3
  - highspy
